const $=id=>document.getElementById(id);
const api=()=>window.go?.gui?.App;
let busy=false,lastState='',activePage='status';
const labels={STARTING:'正在启动',AUTH_REQUIRED:'需要登录',AUTHENTICATING:'正在登录',READY:'已连接',ERROR:'连接异常',STOPPED:'代理未运行'};
function notice(message){$('notice').textContent=String(message||'');$('notice').hidden=!message;}
function page(name){activePage=name;document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('selected',el.dataset.page===name));$('page-title').textContent=document.querySelector('nav button[data-page="'+name+'"]').textContent.trim().slice(1).trim();if(name==='logs')loadLogs();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));
function render(s){lastState=s.state;$('state').textContent=labels[s.state]||s.state;$('status-dot').classList.toggle('ready',s.state==='READY');$('account-value').textContent=s.account||'尚未登录';$('node-value').textContent=s.node||'—';$('address-value').textContent=s.address||'—';$('command').textContent='ssh '+(s.alias||'seusc');$('state-description').textContent=s.state==='READY'?'连接已就绪，现在可以打开终端开始工作。':s.state==='AUTHENTICATING'?'正在获取登录会话。若出现浏览器窗口，请完成所需验证。':'启动后台代理并登录 SEU 账号，建立你的本地 SSH 入口。';$('start').hidden=s.state!=='STOPPED';$('restart').hidden=s.state==='STOPPED';$('stop').hidden=s.state==='STOPPED';if(document.activeElement!==$('username')&&!$('username').value)$('username').value=s.account||'';if(!busy){$('autostart').checked=!!s.autostart;$('login-autostart').checked=s.autostart!==false;}
const nodes=Object.entries(s.nodes||{});if(JSON.stringify(nodes)!==$('nodes').dataset.nodes){$('nodes').replaceChildren(...nodes.map(([name,id])=>{const o=document.createElement('option');o.value=name;o.textContent=name+' · '+id;return o;}));$('nodes').dataset.nodes=JSON.stringify(nodes);} $('nodes').value=s.node||'';}
async function refresh(){if(!api()){notice('请在 SEU SC Bridge 桌面应用中打开此界面。');render({state:'STOPPED'});return;}try{render(await api().Status());}catch(e){render({state:'STOPPED'});}}
async function action(fn){if(busy)return;busy=true;notice('');document.querySelectorAll('button:not(nav button)').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);await refresh();}}
$('login-form').onsubmit=e=>{e.preventDefault();const password=$('password').value;$('password').value='';action(async()=>{notice('正在登录，请稍候…');await api().Login($('username').value.trim(),password,$('remember').checked,$('login-autostart').checked);notice('');page('status');});};
$('start').onclick=()=>action(()=>api().Start());$('restart').onclick=()=>action(()=>api().Restart());$('stop').onclick=()=>action(()=>api().Stop());$('logout').onclick=()=>action(()=>api().Logout());$('copy').onclick=()=>action(async()=>{await api().CopyCommand();notice('已复制 SSH 命令。');});$('nodes').onchange=()=>action(()=>api().SetNode($('nodes').value,0));$('node-form').onsubmit=e=>{e.preventDefault();action(()=>api().SetNode($('new-node').value.trim(),Number($('new-node-id').value)));};$('autostart').onchange=()=>action(()=>api().SetAutoStart($('autostart').checked));async function loadLogs(){if(!api())return;try{$('log-output').textContent=await api().Logs()||'暂无日志';}catch(e){$('log-output').textContent=String(e);}}$('refresh-logs').onclick=loadLogs;refresh();setInterval(refresh,2500);
