//go:build ignore

// Mechanical application icon conversion. Run from the repository root: go run scripts/icons.go
package main
import("bytes";"encoding/binary";"image";"image/color";"image/png";"os";"fmt")
func must(e error){if e!=nil{panic(e)}}
func main(){f,e:=os.Open("frontend/assets/app-icon.png");must(e);src,e:=png.Decode(f);must(e);f.Close();sizes:=[]int{16,24,32,48,64,128,256,512,1024};encoded:=map[int][]byte{}
 for _,size:=range sizes{im:=image.NewNRGBA(image.Rect(0,0,size,size));b:=src.Bounds();for y:=0;y<size;y++{for x:=0;x<size;x++{x0,x1:=x*b.Dx()/size,(x+1)*b.Dx()/size;y0,y1:=y*b.Dy()/size,(y+1)*b.Dy()/size;if x1<=x0{x1=x0+1};if y1<=y0{y1=y0+1};var r,g,bl,a,n uint64;for sy:=y0;sy<y1;sy++{for sx:=x0;sx<x1;sx++{rr,gg,bb,aa:=src.At(sx+b.Min.X,sy+b.Min.Y).RGBA();r+=uint64(rr);g+=uint64(gg);bl+=uint64(bb);a+=uint64(aa);n++}};c:=color.NRGBA{};if a>0{c=color.NRGBA{uint8(r*255/a),uint8(g*255/a),uint8(bl*255/a),uint8(a/n/257)}};im.SetNRGBA(x,y,c)}};var out bytes.Buffer;must(png.Encode(&out,im));encoded[size]=out.Bytes()}
 var ico bytes.Buffer;isizes:=sizes[:7];must(binary.Write(&ico,binary.LittleEndian,[]uint16{0,1,uint16(len(isizes))}));offset:=6+16*len(isizes);for _,size:=range isizes{ico.Write([]byte{byte(size),byte(size),0,0});must(binary.Write(&ico,binary.LittleEndian,uint16(1)));must(binary.Write(&ico,binary.LittleEndian,uint16(32)));must(binary.Write(&ico,binary.LittleEndian,uint32(len(encoded[size]))));must(binary.Write(&ico,binary.LittleEndian,uint32(offset)));offset+=len(encoded[size])};for _,size:=range isizes{ico.Write(encoded[size])};must(os.WriteFile("frontend/assets/app-icon.ico",ico.Bytes(),0644))
 var chunks bytes.Buffer;for _,entry:=range []struct{size int;kind string}{{16,"icp4"},{32,"icp5"},{64,"icp6"},{128,"ic07"},{256,"ic08"},{512,"ic09"},{1024,"ic10"}}{chunks.WriteString(entry.kind);must(binary.Write(&chunks,binary.BigEndian,uint32(8+len(encoded[entry.size]))));chunks.Write(encoded[entry.size])};var icns bytes.Buffer;icns.WriteString("icns");must(binary.Write(&icns,binary.BigEndian,uint32(8+chunks.Len())));icns.Write(chunks.Bytes());must(os.WriteFile("packaging/macos/app-icon.icns",icns.Bytes(),0644));must(os.WriteFile("docs/assets/app-icon-preview.png",encoded[256],0644));fmt.Println("Generated ICO (16–256), ICNS (16–1024) and preview PNGs")}
